# Generated by Django 5.0.1 on 2024-01-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_question_options_alter_question_quesiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesiton',
            new_name='question',
        ),
    ]
